"""add missing relationship discount table

Revision ID: 1108a2a4b143
Revises: 239585e6f2a2
Create Date: 2024-01-15 15:49:49.764167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1108a2a4b143'
down_revision: Union[str, None] = '239585e6f2a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discount_codes', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'discount_codes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'discount_codes', type_='foreignkey')
    op.drop_column('discount_codes', 'user_id')
    # ### end Alembic commands ###
