"""remove employess id

Revision ID: efce5cac8dae
Revises: 1108a2a4b143
Create Date: 2024-01-15 15:52:00.274844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'efce5cac8dae'
down_revision: Union[str, None] = '1108a2a4b143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('employees_ibfk_1', 'employees', type_='foreignkey')
    op.drop_column('employees', 'employee_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('employee_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('employees_ibfk_1', 'employees', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
